stages:
  - test
  - build
  - update

unit-tests:
  stage: test
  cache:
    paths:
      - node_modules
  image: registry.ik8s.ir/node:18-alpine
  script:
    - yarn
    - yarn jest --coverage
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags:
    - novincloud-docker-runner
  artifacts:
    when: on_success
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: '/Lines\s*:\s*(\d+.?\d*)%/'
e2e-tests:
  stage: test
  image: registry.ik8s.ir/node:18-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn
    - yarn jest --version
    - yarn jest --config ./test/jest-e2e.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  tags:
    - novincloud-docker-runner

build-docker-image:
  stage: build
  script:
    - echo $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker image push $CI_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker image prune -f
  only:
    - /^[0-9]+(?:.[0-9]+)+-(rc|stable)(.*)$/
  tags:
    - novincloud-runner

update-helm-release-candidate:
  stage: update
  variables:
    IK8S_CI_IMAGE_NAME: '$CI_PROJECT_NAME'
    IK8S_CI_IMAGE_TAG: '$CI_COMMIT_TAG'
    IK8S_CI_TRIGGER: 'true'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+(?:.[0-9]+)+-(rc)(.*)$/'
  trigger:
    project: ik8s/gitops
    branch: staging

update-helm-stable-release:
  stage: update
  variables:
    IK8S_CI_IMAGE_NAME: '$CI_PROJECT_NAME'
    IK8S_CI_IMAGE_TAG: '$CI_COMMIT_TAG'
    IK8S_CI_TRIGGER: 'true'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+(?:.[0-9]+)+-(stable)(.*)$/'
  trigger:
    project: ik8s/gitops
    branch: main
